-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity blind_axi_split_module is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    in0_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in0_TVALID : IN STD_LOGIC;
    in0_TREADY : OUT STD_LOGIC;
    in0_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    in0_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    in0_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    out0_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out0_TVALID : OUT STD_LOGIC;
    out0_TREADY : IN STD_LOGIC;
    out0_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    out0_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    out0_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    out1_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out1_TVALID : OUT STD_LOGIC;
    out1_TREADY : IN STD_LOGIC;
    out1_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    out1_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    out1_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of blind_axi_split_module is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "blind_axi_split_module_blind_axi_split_module,hls_ip_2021_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-3,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=0.000000,HLS_SYN_LAT=1,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2,HLS_SYN_LUT=39,HLS_VERSION=2021_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;

    signal ap_rst_n_inv : STD_LOGIC;
    signal in0_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal out0_TDATA_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal out1_TDATA_blk_n : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state1_io : BOOLEAN;
    signal regslice_both_out0_V_data_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out1_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state2_io : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal regslice_both_in0_V_data_V_U_apdone_blk : STD_LOGIC;
    signal in0_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal in0_TVALID_int_regslice : STD_LOGIC;
    signal in0_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_in0_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in0_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal in0_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in0_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in0_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in0_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal in0_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in0_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in0_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in0_V_last_V_U_apdone_blk : STD_LOGIC;
    signal in0_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in0_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in0_V_last_V_U_ack_in : STD_LOGIC;
    signal out0_TVALID_int_regslice : STD_LOGIC;
    signal out0_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_out0_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out0_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out0_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out0_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out0_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out0_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out0_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out0_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out0_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out0_V_last_V_U_vld_out : STD_LOGIC;
    signal out1_TVALID_int_regslice : STD_LOGIC;
    signal out1_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_out1_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out1_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out1_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out1_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out1_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out1_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out1_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out1_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out1_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out1_V_last_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component blind_axi_split_module_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    regslice_both_in0_V_data_V_U : component blind_axi_split_module_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in0_TDATA,
        vld_in => in0_TVALID,
        ack_in => regslice_both_in0_V_data_V_U_ack_in,
        data_out => in0_TDATA_int_regslice,
        vld_out => in0_TVALID_int_regslice,
        ack_out => in0_TREADY_int_regslice,
        apdone_blk => regslice_both_in0_V_data_V_U_apdone_blk);

    regslice_both_in0_V_keep_V_U : component blind_axi_split_module_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in0_TKEEP,
        vld_in => in0_TVALID,
        ack_in => regslice_both_in0_V_keep_V_U_ack_in,
        data_out => in0_TKEEP_int_regslice,
        vld_out => regslice_both_in0_V_keep_V_U_vld_out,
        ack_out => in0_TREADY_int_regslice,
        apdone_blk => regslice_both_in0_V_keep_V_U_apdone_blk);

    regslice_both_in0_V_strb_V_U : component blind_axi_split_module_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in0_TSTRB,
        vld_in => in0_TVALID,
        ack_in => regslice_both_in0_V_strb_V_U_ack_in,
        data_out => in0_TSTRB_int_regslice,
        vld_out => regslice_both_in0_V_strb_V_U_vld_out,
        ack_out => in0_TREADY_int_regslice,
        apdone_blk => regslice_both_in0_V_strb_V_U_apdone_blk);

    regslice_both_in0_V_last_V_U : component blind_axi_split_module_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in0_TLAST,
        vld_in => in0_TVALID,
        ack_in => regslice_both_in0_V_last_V_U_ack_in,
        data_out => in0_TLAST_int_regslice,
        vld_out => regslice_both_in0_V_last_V_U_vld_out,
        ack_out => in0_TREADY_int_regslice,
        apdone_blk => regslice_both_in0_V_last_V_U_apdone_blk);

    regslice_both_out0_V_data_V_U : component blind_axi_split_module_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in0_TDATA_int_regslice,
        vld_in => out0_TVALID_int_regslice,
        ack_in => out0_TREADY_int_regslice,
        data_out => out0_TDATA,
        vld_out => regslice_both_out0_V_data_V_U_vld_out,
        ack_out => out0_TREADY,
        apdone_blk => regslice_both_out0_V_data_V_U_apdone_blk);

    regslice_both_out0_V_keep_V_U : component blind_axi_split_module_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in0_TKEEP_int_regslice,
        vld_in => out0_TVALID_int_regslice,
        ack_in => regslice_both_out0_V_keep_V_U_ack_in_dummy,
        data_out => out0_TKEEP,
        vld_out => regslice_both_out0_V_keep_V_U_vld_out,
        ack_out => out0_TREADY,
        apdone_blk => regslice_both_out0_V_keep_V_U_apdone_blk);

    regslice_both_out0_V_strb_V_U : component blind_axi_split_module_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in0_TSTRB_int_regslice,
        vld_in => out0_TVALID_int_regslice,
        ack_in => regslice_both_out0_V_strb_V_U_ack_in_dummy,
        data_out => out0_TSTRB,
        vld_out => regslice_both_out0_V_strb_V_U_vld_out,
        ack_out => out0_TREADY,
        apdone_blk => regslice_both_out0_V_strb_V_U_apdone_blk);

    regslice_both_out0_V_last_V_U : component blind_axi_split_module_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in0_TLAST_int_regslice,
        vld_in => out0_TVALID_int_regslice,
        ack_in => regslice_both_out0_V_last_V_U_ack_in_dummy,
        data_out => out0_TLAST,
        vld_out => regslice_both_out0_V_last_V_U_vld_out,
        ack_out => out0_TREADY,
        apdone_blk => regslice_both_out0_V_last_V_U_apdone_blk);

    regslice_both_out1_V_data_V_U : component blind_axi_split_module_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in0_TDATA_int_regslice,
        vld_in => out1_TVALID_int_regslice,
        ack_in => out1_TREADY_int_regslice,
        data_out => out1_TDATA,
        vld_out => regslice_both_out1_V_data_V_U_vld_out,
        ack_out => out1_TREADY,
        apdone_blk => regslice_both_out1_V_data_V_U_apdone_blk);

    regslice_both_out1_V_keep_V_U : component blind_axi_split_module_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in0_TKEEP_int_regslice,
        vld_in => out1_TVALID_int_regslice,
        ack_in => regslice_both_out1_V_keep_V_U_ack_in_dummy,
        data_out => out1_TKEEP,
        vld_out => regslice_both_out1_V_keep_V_U_vld_out,
        ack_out => out1_TREADY,
        apdone_blk => regslice_both_out1_V_keep_V_U_apdone_blk);

    regslice_both_out1_V_strb_V_U : component blind_axi_split_module_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in0_TSTRB_int_regslice,
        vld_in => out1_TVALID_int_regslice,
        ack_in => regslice_both_out1_V_strb_V_U_ack_in_dummy,
        data_out => out1_TSTRB,
        vld_out => regslice_both_out1_V_strb_V_U_vld_out,
        ack_out => out1_TREADY,
        apdone_blk => regslice_both_out1_V_strb_V_U_apdone_blk);

    regslice_both_out1_V_last_V_U : component blind_axi_split_module_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in0_TLAST_int_regslice,
        vld_in => out1_TVALID_int_regslice,
        ack_in => regslice_both_out1_V_last_V_U_ack_in_dummy,
        data_out => out1_TLAST,
        vld_out => regslice_both_out1_V_last_V_U_vld_out,
        ack_out => out1_TREADY,
        apdone_blk => regslice_both_out1_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, regslice_both_out0_V_data_V_U_apdone_blk, regslice_both_out1_V_data_V_U_apdone_blk, in0_TVALID_int_regslice, out0_TREADY_int_regslice, out1_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((regslice_both_out1_V_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_out0_V_data_V_U_apdone_blk = ap_const_logic_1) or (out1_TREADY_int_regslice = ap_const_logic_0) or (out0_TREADY_int_regslice = ap_const_logic_0))) or ((ap_const_logic_1 = ap_const_logic_1) and ((out1_TREADY_int_regslice = ap_const_logic_0) or (out0_TREADY_int_regslice = ap_const_logic_0) or (in0_TVALID_int_regslice = ap_const_logic_0))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state1_io, regslice_both_out0_V_data_V_U_apdone_blk, regslice_both_out1_V_data_V_U_apdone_blk, ap_block_state2_io, in0_TVALID_int_regslice, out0_TREADY_int_regslice, out1_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((regslice_both_out1_V_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_out0_V_data_V_U_apdone_blk = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state2_io) or (out1_TREADY_int_regslice = ap_const_logic_0) or (out0_TREADY_int_regslice = ap_const_logic_0))) or ((ap_const_logic_1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state1_io) or (out1_TREADY_int_regslice = ap_const_logic_0) or (out0_TREADY_int_regslice = ap_const_logic_0) or (in0_TVALID_int_regslice = ap_const_logic_0))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state1_io, regslice_both_out0_V_data_V_U_apdone_blk, regslice_both_out1_V_data_V_U_apdone_blk, ap_block_state2_io, in0_TVALID_int_regslice, out0_TREADY_int_regslice, out1_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((regslice_both_out1_V_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_out0_V_data_V_U_apdone_blk = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state2_io) or (out1_TREADY_int_regslice = ap_const_logic_0) or (out0_TREADY_int_regslice = ap_const_logic_0))) or ((ap_const_logic_1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state1_io) or (out1_TREADY_int_regslice = ap_const_logic_0) or (out0_TREADY_int_regslice = ap_const_logic_0) or (in0_TVALID_int_regslice = ap_const_logic_0))));
    end process;


    ap_block_state1_io_assign_proc : process(out0_TREADY_int_regslice, out1_TREADY_int_regslice)
    begin
                ap_block_state1_io <= ((out1_TREADY_int_regslice = ap_const_logic_0) or (out0_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(in0_TVALID_int_regslice, out0_TREADY_int_regslice, out1_TREADY_int_regslice)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((out1_TREADY_int_regslice = ap_const_logic_0) or (out0_TREADY_int_regslice = ap_const_logic_0) or (in0_TVALID_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state2_io_assign_proc : process(out0_TREADY_int_regslice, out1_TREADY_int_regslice)
    begin
                ap_block_state2_io <= ((out1_TREADY_int_regslice = ap_const_logic_0) or (out0_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(regslice_both_out0_V_data_V_U_apdone_blk, regslice_both_out1_V_data_V_U_apdone_blk, out0_TREADY_int_regslice, out1_TREADY_int_regslice)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((regslice_both_out1_V_data_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_out0_V_data_V_U_apdone_blk = ap_const_logic_1) or (out1_TREADY_int_regslice = ap_const_logic_0) or (out0_TREADY_int_regslice = ap_const_logic_0));
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_logic_1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_reset_idle_pp0 <= ap_const_logic_0;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    in0_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, in0_TVALID_int_regslice)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in0_TDATA_blk_n <= in0_TVALID_int_regslice;
        else 
            in0_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    in0_TREADY <= regslice_both_in0_V_data_V_U_ack_in;

    in0_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in0_TREADY_int_regslice <= ap_const_logic_1;
        else 
            in0_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    out0_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter1, out0_TREADY_int_regslice)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            out0_TDATA_blk_n <= out0_TREADY_int_regslice;
        else 
            out0_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out0_TVALID <= regslice_both_out0_V_data_V_U_vld_out;

    out0_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            out0_TVALID_int_regslice <= ap_const_logic_1;
        else 
            out0_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    out1_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter1, out1_TREADY_int_regslice)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            out1_TDATA_blk_n <= out1_TREADY_int_regslice;
        else 
            out1_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out1_TVALID <= regslice_both_out1_V_data_V_U_vld_out;

    out1_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            out1_TVALID_int_regslice <= ap_const_logic_1;
        else 
            out1_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

end behav;
