#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("main_in_TDATA", 32, hls_in, 0, "axis", "in_data", 1),
	Port_Property("main_in_TVALID", 1, hls_in, 3, "axis", "in_vld", 1),
	Port_Property("main_in_TREADY", 1, hls_out, 3, "axis", "in_acc", 1),
	Port_Property("main_in_TKEEP", 4, hls_in, 1, "axis", "in_data", 1),
	Port_Property("main_in_TSTRB", 4, hls_in, 2, "axis", "in_data", 1),
	Port_Property("main_in_TLAST", 1, hls_in, 3, "axis", "in_data", 1),
	Port_Property("aux_in_TDATA", 32, hls_in, 4, "axis", "in_data", 1),
	Port_Property("aux_in_TVALID", 1, hls_in, 7, "axis", "in_vld", 1),
	Port_Property("aux_in_TREADY", 1, hls_out, 7, "axis", "in_acc", 1),
	Port_Property("aux_in_TKEEP", 4, hls_in, 5, "axis", "in_data", 1),
	Port_Property("aux_in_TSTRB", 4, hls_in, 6, "axis", "in_data", 1),
	Port_Property("aux_in_TLAST", 1, hls_in, 7, "axis", "in_data", 1),
	Port_Property("output_r_TDATA", 32, hls_out, 8, "axis", "out_data", 1),
	Port_Property("output_r_TVALID", 1, hls_out, 11, "axis", "out_vld", 1),
	Port_Property("output_r_TREADY", 1, hls_in, 11, "axis", "out_acc", 1),
	Port_Property("output_r_TKEEP", 4, hls_out, 9, "axis", "out_data", 1),
	Port_Property("output_r_TSTRB", 4, hls_out, 10, "axis", "out_data", 1),
	Port_Property("output_r_TLAST", 1, hls_out, 11, "axis", "out_data", 1),
	Port_Property("mu", 32, hls_in, 12, "ap_none", "in_data", 1),
};
const char* HLS_Design_Meta::dut_name = "nlms_module_3tap";
